;;Luca Sortino, bauyrzhan zhakanov, Giacomo Lugano (jek.lugano@yahoo.com)
(define (problem instance_4)

(:domain coffee_robot)

	(:objects
        ;; specific of the problem
		d1 -drink
        d2 -drink
        d3 -drink
        d4 -drink
        d5 -drink
        d6 -drink
        d7 -drink
        d8 -drink

        ;; general of the assignment
        b -table 
        t1 -table
        t2 -table
        t3 -table
        t4 -table

        wr -robot 
        br -robot 

	)

    (:init
        (cold_drink d1)
        (cold_drink d2)
        (hot_drink d3)
        (hot_drink d4)
        (hot_drink d5)
        (hot_drink d6)
        (cold_drink d7)
        (cold_drink d8)
        (= (drink_temperature d1) 0)
        (= (drink_temperature d2) 0)
        (= (drink_temperature d3) 0)
        (= (drink_temperature d4) 0)
        (= (drink_temperature d5) 0)
        (= (drink_temperature d6) 0)
        (= (drink_temperature d7) 0)
        (= (drink_temperature d8) 0)

        (clean b)
        (clean t1)
        (clean t2)
        (clean t4)
        (bar b)
        (= (xt b) 1)
        (= (yt b) 4)
        (= (t_dim b) 2)
        (= (xt t1) 1)
        (= (yt t1) 2)
        (= (t_dim t1) 1)
        (= (xt t2) 2)
        (= (yt t2) 2)
        (= (t_dim t2) 1)
        (= (xt t3) 1)
        (= (yt t3) 1)
        (= (t_dim t3) 2)
        (= (xt t4) 2)
        (= (yt t4) 1)
        (= (t_dim t4) 1)
        (= (x_min) 0)
        (= (y_min) 0)
        (= (x_max) 3)
        (= (y_max) 5)

        (waiter wr)
        (barista br)
        (= (holding wr) 0)
        (= (holding br) 0)
        (= (xr wr) 1) 
        (= (yr wr) 4)
        (= (xr br) 1) 
        (= (yr br) 4)

        (= (p_c_d_c d1 b) 0)
        (= (p_c_d_c d1 t1) 0)
        (= (p_c_d_c d1 t2) 0)
        (= (p_c_d_c d1 t3) 0)
        (= (p_c_d_c d1 t4) 0)
        (= (p_c_d_c d2 b) 0)
        (= (p_c_d_c d2 t1) 0)
        (= (p_c_d_c d2 t2) 0)
        (= (p_c_d_c d2 t3) 0)
        (= (p_c_d_c d2 t4) 0)

        (= (p_h_d_c d1 b) 0)
        (= (p_h_d_c d1 t1) 0)
        (= (p_h_d_c d1 t2) 0)
        (= (p_h_d_c d1 t3) 0)
        (= (p_h_d_c d1 t4) 0)
        (= (p_h_d_c d2 b) 0)
        (= (p_h_d_c d2 t1) 0)
        (= (p_h_d_c d2 t2) 0)
        (= (p_h_d_c d2 t3) 0)
        (= (p_h_d_c d2 t4) 0)

        (= (p_c_d_c d3 b) 0)
        (= (p_c_d_c d3 t1) 0)
        (= (p_c_d_c d3 t2) 0)
        (= (p_c_d_c d3 t3) 0)
        (= (p_c_d_c d3 t4) 0)
        (= (p_c_d_c d4 b) 0)
        (= (p_c_d_c d4 t1) 0)
        (= (p_c_d_c d4 t2) 0)
        (= (p_c_d_c d4 t3) 0)
        (= (p_c_d_c d4 t4) 0)

        (= (p_h_d_c d3 b) 0)
        (= (p_h_d_c d3 t1) 0)
        (= (p_h_d_c d3 t2) 0)
        (= (p_h_d_c d3 t3) 0)
        (= (p_h_d_c d3 t4) 0)
        (= (p_h_d_c d4 b) 0)
        (= (p_h_d_c d4 t1) 0)
        (= (p_h_d_c d4 t2) 0)
        (= (p_h_d_c d4 t3) 0)
        (= (p_h_d_c d4 t4) 0)

        (= (p_c_d_c d5 b) 0)
        (= (p_c_d_c d5 t1) 0)
        (= (p_c_d_c d5 t2) 0)
        (= (p_c_d_c d5 t3) 0)
        (= (p_c_d_c d5 t4) 0)
        (= (p_c_d_c d6 b) 0)
        (= (p_c_d_c d6 t1) 0)
        (= (p_c_d_c d6 t2) 0)
        (= (p_c_d_c d6 t3) 0)
        (= (p_c_d_c d6 t4) 0)

        (= (p_h_d_c d5 b) 0)
        (= (p_h_d_c d5 t1) 0)
        (= (p_h_d_c d5 t2) 0)
        (= (p_h_d_c d5 t3) 0)
        (= (p_h_d_c d5 t4) 0)
        (= (p_h_d_c d6 b) 0)
        (= (p_h_d_c d6 t1) 0)
        (= (p_h_d_c d6 t2) 0)
        (= (p_h_d_c d6 t3) 0)
        (= (p_h_d_c d6 t4) 0)

        (= (p_c_d_c d7 b) 0)
        (= (p_c_d_c d7 t1) 0)
        (= (p_c_d_c d7 t2) 0)
        (= (p_c_d_c d7 t3) 0)
        (= (p_c_d_c d7 t4) 0)
        (= (p_c_d_c d8 b) 0)
        (= (p_c_d_c d8 t1) 0)
        (= (p_c_d_c d8 t2) 0)
        (= (p_c_d_c d8 t3) 0)
        (= (p_c_d_c d8 t4) 0)

        (= (p_h_d_c d7 b) 0)
        (= (p_h_d_c d7 t1) 0)
        (= (p_h_d_c d7 t2) 0)
        (= (p_h_d_c d7 t3) 0)
        (= (p_h_d_c d7 t4) 0)
        (= (p_h_d_c d8 b) 0)
        (= (p_h_d_c d8 t1) 0)
        (= (p_h_d_c d8 t2) 0)
        (= (p_h_d_c d8 t3) 0)
        (= (p_h_d_c d8 t4) 0)
        
        (= (c_C wr b) 0)
        (= (c_C wr t1) 0)
        (= (c_C wr t2) 0)
        (= (c_C wr t3) 0)
        (= (c_C wr t4) 0)
        (= (c_C br b) 0)
        (= (c_C br t1) 0)
        (= (c_C br t2) 0)
        (= (c_C br t3) 0)
        (= (c_C br t4) 0)

        (= (m_uf_C wr) 0)
        (= (m_urf_C wr) 0)
        (= (m_rf_C wr) 0) 
        (= (m_drf_C wr) 0)
        (= (m_df_C wr) 0) 
        (= (m_dlf_C wr) 0)
        (= (m_lf_C wr) 0) 
        (= (m_ulf_C wr) 0)
        (= (m_us_C wr) 0) 
        (= (m_urs_C wr) 0)
        (= (m_rs_C wr) 0) 
        (= (m_drs_C wr) 0)
        (= (m_ds_C wr) 0) 
        (= (m_dls_C wr) 0)
        (= (m_ls_C wr) 0) 
        (= (m_uls_C wr) 0) 

        (= (m_uf_C br) 0)
        (= (m_urf_C br) 0)
        (= (m_rf_C br) 0) 
        (= (m_drf_C br) 0)
        (= (m_df_C br) 0) 
        (= (m_dlf_C br) 0)
        (= (m_lf_C br) 0) 
        (= (m_ulf_C br) 0)
        (= (m_us_C br) 0) 
        (= (m_urs_C br) 0)
        (= (m_rs_C br) 0) 
        (= (m_drs_C br) 0)
        (= (m_ds_C br) 0) 
        (= (m_dls_C br) 0)
        (= (m_ls_C br) 0) 
        (= (m_uls_C br) 0)     
    
    )

	(:goal
        (and (served_cold_drink d1 t1) (served_cold_drink d2 t1) (served_hot_drink d3 t3) (served_hot_drink d4 t3) (served_hot_drink d5 t3) (served_hot_drink d6 t3) (served_cold_drink d7 t4) (served_cold_drink d8 t4) (clean t3))
        
    )
)